version: '3.8'

services:
  user-management-service:
    build: .
    container_name: user-management-service
    depends_on:
      - user-db
    ports:
      - target: 8090
        published: 8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc.postgresql://user-db:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  user-db:
      image: postgres
      container_name: user-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root